name: sql
channels:
  - conda-forge
  - anaconda
dependencies:
  - postgresql
  - postgis
  - netcdf4
  - xarray
  - dask
  - numpy
  - pandas
  - psycopg2
  - pip
  - spyder 
  - matplotlib
  - cartopy
  - postgis
